### ISSUE TITLE
Relay输出的一个问题

### ISSUE THREAD

**Issue by nineis7** [xiayouran/VisuTVM#4]
对Relay进行BindParams后就会出现以下报错：
```
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    visu_relay_ir(before_pass, after_pass, save_name, with_info)
  File "/home/nineis/ws/gpt-frontend/VisuTVM/utils.py", line 53, in visu_relay_ir
    g.codegen()
  File "/home/nineis/ws/gpt-frontend/VisuTVM/visu_tvm.py", line 104, in codegen
    self.get_tensor_info(self.txt_file)
  File "/home/nineis/ws/gpt-frontend/VisuTVM/visu_tvm.py", line 255, in get_tensor_info
    info = match_res[0].split(', ')
IndexError: list index out of range
```
是不是要保证fn的input参数不被绑定呀，有没有办法可以正常识别出BindParams后的IR？

**Comment by nineis7** [comment]
喔这个问题不是BindPass导致的，是加了”-wi“导致的
